name: Deploy to Azure App Service

on:
  push:
    branches:
      - main  # Nhánh chính sẽ kích hoạt hành động

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0'  # Sử dụng .NET 9

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --no-restore --configuration Release

    - name: Publish the project
      run: dotnet publish -c Release -o ${{ github.workspace }}/publish

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: <Your-App-Service-Name>  # Tên App Service trong Azure
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ github.workspace }}/publish